from typing import Dict, Optional

IPC_BNS_MAP: Dict[str, Dict[str, str]] = {
    "1": {"bns": "N/A", "description": "Introduction, extent and enforcement of the Code"},
    "2": {"bns": "N/A", "description": "Punishment of offences committed within India"},
    "3": {"bns": "N/A", "description": "Punishment of offences committed beyond India"},
    "34": {"bns": "3(5)", "description": "Acts done by several persons in furtherance of common intention"},
    "36": {"bns": "N/A", "description": "Voluntarily causing hurt"},
    "100": {"bns": "N/A", "description": "Murder"},
    "101": {"bns": "N/A", "description": "Punishment for murder"},
    "120A": {"bns": "61", "description": "Criminal conspiracy definition"},
    "120B": {"bns": "61", "description": "Punishment for criminal conspiracy"},
    "141": {"bns": "189", "description": "Unlawful assembly"},
    "142": {"bns": "190", "description": "Being member of unlawful assembly"},
    "143": {"bns": "191", "description": "Punishment for unlawful assembly"},
    "144": {"bns": "191", "description": "Joining unlawful assembly with deadly weapon"},
    "147": {"bns": "191", "description": "Punishment for rioting"},
    "148": {"bns": "191", "description": "Rioting armed with deadly weapon"},
    "149": {"bns": "191", "description": "Every member of unlawful assembly guilty of offence"},
    "160": {"bns": "141", "description": "Affray"},
    "299": {"bns": "100", "description": "Culpable homicide"},
    "300": {"bns": "101", "description": "Murder"},
    "302": {"bns": "103(1)", "description": "Punishment for murder"},
    "303": {"bns": "103(2)", "description": "Punishment for murder by life-convict"},
    "304": {"bns": "105", "description": "Punishment for culpable homicide not amounting to murder"},
    "304A": {"bns": "106", "description": "Causing death by negligence"},
    "306": {"bns": "108", "description": "Abetment of suicide"},
    "307": {"bns": "109", "description": "Attempt to murder"},
    "308": {"bns": "110", "description": "Attempt to commit culpable homicide"},
    "309": {"bns": "N/A", "description": "Attempt to commit suicide (repealed)"},
    "312": {"bns": "N/A", "description": "Causing miscarriage"},
    "314": {"bns": "N/A", "description": "Death caused by act done with intent to cause miscarriage"},
    "316": {"bns": "N/A", "description": "Causing death of quick child"},
    "318": {"bns": "N/A", "description": "Concealment of birth by secret disposal of dead body"},
    "319": {"bns": "N/A", "description": "Hurt"},
    "320": {"bns": "114", "description": "Grievous hurt"},
    "321": {"bns": "115", "description": "Voluntarily causing hurt"},
    "322": {"bns": "116", "description": "Voluntarily causing grievous hurt"},
    "323": {"bns": "117", "description": "Punishment for voluntarily causing hurt"},
    "324": {"bns": "118", "description": "Voluntarily causing hurt by dangerous weapons"},
    "325": {"bns": "119", "description": "Punishment for voluntarily causing grievous hurt"},
    "326": {"bns": "120", "description": "Voluntarily causing grievous hurt by dangerous weapons"},
    "328": {"bns": "121", "description": "Causing hurt by means of poison"},
    "329": {"bns": "122", "description": "Voluntarily causing grievous hurt to extort confession"},
    "330": {"bns": "123", "description": "Voluntarily causing hurt to extort confession"},
    "331": {"bns": "124", "description": "Voluntarily causing grievous hurt to extort confession"},
    "332": {"bns": "125", "description": "Voluntarily causing hurt to deter public servant"},
    "333": {"bns": "126", "description": "Voluntarily causing grievous hurt to deter public servant"},
    "334": {"bns": "127", "description": "Voluntarily causing hurt on provocation"},
    "335": {"bns": "128", "description": "Voluntarily causing grievous hurt on provocation"},
    "336": {"bns": "129", "description": "Act endangering life or personal safety"},
    "337": {"bns": "130", "description": "Causing hurt by act endangering life"},
    "338": {"bns": "131", "description": "Causing grievous hurt by act endangering life"},
    "341": {"bns": "137", "description": "Wrongful restraint"},
    "342": {"bns": "138", "description": "Wrongful confinement"},
    "343": {"bns": "139", "description": "Punishment for wrongful confinement"},
    "344": {"bns": "140", "description": "Wrongful confinement for 3+ days"},
    "346": {"bns": "142", "description": "Wrongful confinement in secret"},
    "348": {"bns": "143", "description": "Wrongful confinement to extort confession"},
    "352": {"bns": "132", "description": "Criminal force on provocation"},
    "354": {"bns": "74", "description": "Assault or criminal force to woman with intent to outrage modesty"},
    "354A": {"bns": "75", "description": "Sexual harassment"},
    "354B": {"bns": "76", "description": "Assault with intent to disrobe"},
    "354C": {"bns": "77", "description": "Voyeurism"},
    "354D": {"bns": "78", "description": "Stalking"},
    "362": {"bns": "144", "description": "Abduction"},
    "363": {"bns": "137", "description": "Punishment for kidnapping"},
    "364": {"bns": "138", "description": "Kidnapping for murder"},
    "365": {"bns": "139", "description": "Kidnapping to secretly confine"},
    "366": {"bns": "140", "description": "Kidnapping woman to compel marriage"},
    "368": {"bns": "142", "description": "Wrongful confinement of kidnapped person"},
    "370": {"bns": "143", "description": "Trafficking of persons"},
    "371": {"bns": "144", "description": "Habitual dealing in slaves"},
    "372": {"bns": "145", "description": "Selling minor for prostitution"},
    "374": {"bns": "146", "description": "Unlawful compulsory labour"},
    "375": {"bns": "63", "description": "Rape"},
    "376": {"bns": "64", "description": "Punishment for rape"},
    "376A": {"bns": "65", "description": "Punishment for causing death or persistent vegetative state"},
    "376B": {"bns": "66", "description": "Sexual intercourse by husband upon wife during separation"},
    "376C": {"bns": "67", "description": "Sexual intercourse by person in authority"},
    "376D": {"bns": "68", "description": "Gang rape"},
    "376E": {"bns": "70", "description": "Repeat offence of rape"},
    "377": {"bns": "N/A", "description": "Unnatural offences (partially retained)"},
    "379": {"bns": "303", "description": "Theft"},
    "380": {"bns": "304", "description": "Theft in dwelling house"},
    "381": {"bns": "305", "description": "Theft by clerk or servant"},
    "382": {"bns": "306", "description": "Theft after preparation for death or hurt"},
    "383": {"bns": "308", "description": "Extortion"},
    "384": {"bns": "309", "description": "Punishment for extortion"},
    "385": {"bns": "310", "description": "Putting person in fear of injury to commit extortion"},
    "386": {"bns": "311", "description": "Extortion by putting fear of death or grievous hurt"},
    "390": {"bns": "312", "description": "Robbery"},
    "391": {"bns": "313", "description": "Dacoity"},
    "392": {"bns": "314", "description": "Punishment for robbery"},
    "393": {"bns": "315", "description": "Attempt to commit robbery"},
    "394": {"bns": "316", "description": "Voluntarily causing hurt in committing robbery"},
    "395": {"bns": "317", "description": "Punishment for dacoity"},
    "396": {"bns": "318", "description": "Dacoity with murder"},
    "397": {"bns": "319", "description": "Robbery with attempt to cause death or grievous hurt"},
    "398": {"bns": "320", "description": "Attempt to commit robbery with deadly weapon"},
    "399": {"bns": "321", "description": "Making preparation to commit dacoity"},
    "400": {"bns": "322", "description": "Punishment for belonging to gang of dacoits"},
    "403": {"bns": "324", "description": "Dishonest misappropriation of property"},
    "405": {"bns": "326", "description": "Criminal breach of trust"},
    "406": {"bns": "327", "description": "Punishment for criminal breach of trust"},
    "409": {"bns": "330", "description": "Criminal breach of trust by public servant"},
    "410": {"bns": "331", "description": "Stolen property"},
    "411": {"bns": "332", "description": "Dishonestly receiving stolen property"},
    "414": {"bns": "334", "description": "Assisting in concealment of stolen property"},
    "415": {"bns": "336", "description": "Cheating"},
    "417": {"bns": "338", "description": "Punishment for cheating"},
    "418": {"bns": "339", "description": "Cheating in respect of valuable security"},
    "419": {"bns": "340", "description": "Punishment for cheating by personation"},
    "420": {"bns": "341", "description": "Cheating and dishonestly inducing delivery of property"},
    "423": {"bns": "344", "description": "Dishonest removal or concealment of property"},
    "424": {"bns": "345", "description": "Dishonest or fraudulent removal of property"},
    "425": {"bns": "346", "description": "Mischief"},
    "426": {"bns": "347", "description": "Punishment for mischief"},
    "427": {"bns": "348", "description": "Mischief causing damage"},
    "430": {"bns": "350", "description": "Mischief by injury to public works"},
    "435": {"bns": "353", "description": "Mischief by fire or explosive substance"},
    "441": {"bns": "355", "description": "Criminal trespass"},
    "442": {"bns": "356", "description": "House trespass"},
    "447": {"bns": "357", "description": "Punishment for criminal trespass"},
    "448": {"bns": "358", "description": "Punishment for house trespass"},
    "450": {"bns": "359", "description": "House trespass to commit offence"},
    "452": {"bns": "360", "description": "House trespass after preparation for hurt"},
    "453": {"bns": "361", "description": "Punishment for lurking house-trespass or house-breaking"},
    "454": {"bns": "362", "description": "Lurking house-trespass to commit offence"},
    "456": {"bns": "363", "description": "Punishment for lurking house-trespass"},
    "457": {"bns": "364", "description": "Lurking house-trespass by night"},
    "460": {"bns": "366", "description": "Punishment for house-breaking by night"},
    "461": {"bns": "367", "description": "Dishonestly breaking open receptacle"},
    "463": {"bns": "369", "description": "Forgery"},
    "464": {"bns": "370", "description": "Making a false document"},
    "465": {"bns": "371", "description": "Punishment for forgery"},
    "467": {"bns": "372", "description": "Forgery of valuable security or will"},
    "468": {"bns": "373", "description": "Forgery for purpose of cheating"},
    "469": {"bns": "374", "description": "Forgery for purpose of harming reputation"},
    "471": {"bns": "376", "description": "Using forged document as genuine"},
    "474": {"bns": "379", "description": "Having possession of forged document"},
    "477": {"bns": "382", "description": "Fraudulent cancellation or destruction of document"},
    "482": {"bns": "383", "description": "Using false property mark"},
    "489A": {"bns": "N/A", "description": "Counterfeiting currency notes"},
    "489B": {"bns": "N/A", "description": "Using forged currency notes"},
    "491": {"bns": "N/A", "description": "Breach of contract to attend on helpless person"},
    "493": {"bns": "82", "description": "Cohabitation caused by fraudulently induced belief of marriage"},
    "494": {"bns": "82", "description": "Marrying again during lifetime of husband or wife"},
    "495": {"bns": "82", "description": "Same offence with concealment of former marriage"},
    "496": {"bns": "82", "description": "Marriage ceremony fraudulently gone through"},
    "498": {"bns": "85", "description": "Enticing or taking away married woman"},
    "498A": {"bns": "85", "description": "Cruelty by husband or his relatives"},
    "500": {"bns": "356", "description": "Punishment for defamation"},
    "501": {"bns": "357", "description": "Printing defamatory matter"},
    "503": {"bns": "351", "description": "Criminal intimidation"},
    "504": {"bns": "352", "description": "Intentional insult with intent to provoke breach of peace"},
    "505": {"bns": "353", "description": "Statements conducing to public mischief"},
    "506": {"bns": "351", "description": "Punishment for criminal intimidation"},
    "507": {"bns": "351", "description": "Criminal intimidation by anonymous communication"},
    "509": {"bns": "79", "description": "Word, gesture or act intended to insult modesty of woman"},
    "510": {"bns": "80", "description": "Misconduct in public by drunken person"},
    "511": {"bns": "62", "description": "Punishment for attempting to commit offences"},
}

LAW_TYPE_KEYWORDS = {
    "IPC": ["IPC", "Indian Penal Code"],
    "BNS": ["BNS", "Bharatiya Nyaya Sanhita"],
    "CrPC": ["CrPC", "Criminal Procedure Code", "BNSS", "Bharatiya Nagarik Suraksha Sanhita"],
}


def get_bns_mapping(ipc_section: str) -> Optional[Dict[str, str]]:
    clean = ipc_section.strip().upper().replace("SECTION ", "").replace("SEC ", "").replace(".", "")
    mapping = IPC_BNS_MAP.get(clean)
    if mapping:
        return {"ipc": clean, "bns": mapping["bns"], "description": mapping["description"]}
    return None


def detect_law_type(text: str) -> str:
    for law_type, keywords in LAW_TYPE_KEYWORDS.items():
        for kw in keywords:
            if kw.lower() in text.lower():
                return law_type
    return "IPC"
